INSERT INTO Teams VALUES
(1, 'Warriors', 'CA', 'Golden State', 1, 'GSW'), 
(2, 'Lakers', 'CA', 'Los Angeles', 2, 'LAL'), 
(3, 'Clippers', 'CA', 'Los Angeles', 4, 'LAC'), 
(4, 'Suns', 'AZ', 'Phoenix', 5, 'PHX'), 
(5, 'Kings', 'CA', 'Sacramento', 8, 'SAC'), 
(6, 'Jazz', 'UT', 'Utah', 30, 'UTA'), 
(7, 'TimberWolves', 'MN', 'Minnesota', 25, 'MIN'), 
(8, 'Nuggets', 'CO', 'Denver', 24, 'DEN'), 
(9, 'Blazers', 'OR', 'Portland', 19, 'POR'), 
(10, 'Thunder', 'OK', 'Oklahoma City', 26, 'OKC'), 
(11, 'Grizzlies', 'TN', 'Memphis', 27, 'MEM'), 
(12, 'Pelicans', 'LA', 'New Orleans', 28, 'NOP'), 
(13, 'Spurs', 'TX', 'San Antonio', 3, 'SAS'), 
(14, 'Rockets', 'TX', 'Houston', 9, 'HOU'), 
(15, 'Mavericks', 'TX', 'Dallas', 10, 'DAL'), 
(16, 'Celtics', 'MA', 'Boston', 6, 'BOS'), 
(17, 'Raptors', 'CANDA', 'Toronto', 29, 'TOR'), 
(18, '76ers', 'PA', 'Philadelphia', 21, 'PHI'), 
(19, 'Knicks', 'NY', 'New York', 22, 'NYK'), 
(20, 'Nets', 'NY', 'Brooklyn', 14, 'BRK'), 
(21, 'Heat', 'FL', 'Miami', 11, 'MIA'), 
(22, 'Magic', 'FL', 'Orlando', 20, 'ORL'), 
(23, 'Hornets', 'NC', 'Charlotte', 15, 'CHA'), 
(24, 'Hawks', 'GA', 'Atlanta', 13, 'ATL'), 
(25, 'Wizards', 'DC', 'Washington', 18, 'WAS'), 
(26, 'Pistons', 'MI', 'Detroit', 23, 'DET'), 
(27, 'Pacers', 'IN', 'Indiana', 17, 'IND'), 
(28, 'Bulls', 'IL', 'Chicago', 12, 'CHI'), 
(29, 'Cavaliers', 'OH', 'Cleveland', 16, 'CLE'), 
(30, 'Bucks', 'WI', 'Milwaukee', 7, 'MIL'),
(31, 'TRADED', 'TD', 'TRADED', null, 'TRA');